export const characters = [
{src: "T_Agni_Default_Icon.png", name: "Agni" },
{src: "T_AhPuch_Default_Icon.png", name: "Ah Puch" },
{src: "T_Amaterasu_Default_Icon.png", name:"Amaterasu" },
{src: "T_AMC_Default_Icon.png", name:"Ah Muzencab" },
{src: "T_Anhur_Default_Icon.png", name:"Anhur" },
{src: "T_Anubis_Default_Icon.png", name:"Anubis" },
{src: "T_AoKuang_Default_Icon.png", name:"AoKuang" },
{src: "T_Aphrodite_Default_Icon.png", name:"Aphrodite" },
{src: "T_Apollo_Default_Icon.png", name:"Apollo" },
{src: "T_Arachne_Classic_Icon.png", name:"Arachne" },
{src: "T_Ares_Default_Icon.png", name:"Ares" },
{src: "T_Artemis_Default_Icon.png", name:"Artemis" },
{src: "T_Athena_Default_Icon.png", name:"Athena" },
{src: "T_Awilix_Default_Icon.png", name:"Awilix" },
{src: "T_Bacchus_Default_Icon.png", name:"Bacchus" },
{src: "T_Bakasura_Default_Icon.png", name:"Bakasura" },
{src: "T_Bastet_Default_Icon.png", name:"Bastet" },
{src: "T_Bellona_Default_Icon.png", name:"Bellona" },
{src: "T_Cabrakan_Default_Icon.png", name:"Cabrakan" },
{src: "T_Chaac_Default_Icon.png", name:"Chaac" },
{src: "T_ChangE_Default_Icon.png", name:"Chang'e" },
{src: "T_Chiron_Default_Icon.png", name:"Chiron" },
{src: "T_Chronos_Default_Icon.png", name:"Chronos" },
{src: "T_Cupid_Default_Icon.png", name:"Cupid" },
{src: "T_Eset_Default_Icon_Old2.png", name:"Eset" },
{src: "T_Fenrir_Default_Icon.png", name:"Fenrir" },
{src: "T_Freya_Default_Icon.png", name:"Freya" },
{src: "T_Geb_Default_Icon.png", name:"Geb" },
{src: "T_GuanYu_Default_Icon.png", name:"GuanYu" },
{src: "T_Hades_Default_Icon.png", name:"Hades" },
{src: "T_HeBo_Default_Icon.png", name:"HeBo" },
{src: "T_Hel_Default_Icon.png", name:"Hel" },
{src: "T_Hercules_Default_Icon.png", name:"Hercules" },
{src: "T_HouYi_Default_Icon.png", name:"HouYi" },
{src: "T_HunBatz_Default_Icon.png", name:"HunBatz" },
{src: "T_Janus_Default_Icon.png", name:"Janus" },
{src: "T_JingWei_Default_Icon.png", name:"JingWei" },
{src: "T_Kali_Default_Icon.png", name:"Kali" },
{src: "T_Khepri_Default_Icon.png", name:"Khepri" },
{src: "T_Kukulkan_Default_Icon.png", name:"Kukulkan" },
{src: "T_Kumbhakarna_Default_Icon.png", name:"Kumbhakarna" },
{src: "T_Loki_Default_Icon.png", name:"Loki" },
{src: "T_Medusa_Default_Icon.png", name:"Medusa" },
{src: "T_Mercury_Default_Icon.png", name:"Mercury" },
{src: "T_Neith_Default_Icon.png", name:"Neith" },
{src: "T_Nemesis_Default_Icon.png", name:"Nemesis" },
{src: "T_NeZha_Default_Icon.png", name:"NeZha" },
{src: "T_Nox_Default_Icon.png", name:"Nox" },
{src: "T_NuWa_Default_Icon.png", name:"NuWa" },
{src: "T_Odin_Default_Icon.png", name:"Odin" },
{src: "T_Osiris_Default_Icon.png", name:"Osiris" },
{src: "T_Poseidon_Default_Icon.png", name:"Poseidon" },
{src: "T_Raijin_Default_Icon.png", name:"Raijin" },
{src: "T_Ram_Default_Icon.png", name:"Rama" },
{src: "T_Ratatoskr_Default_Icon.png", name:"Ratatoskr" },
{src: "T_Ravana_Default_Icon.png", name:"Ravana" },
{src: "T_Ra_Default_Icon.png", name:"Ra" },
{src: "T_Scylla_Default_Icon.png", name:"Scylla" },
{src: "T_Serqet_Default_Icon.png", name:"Serqet" },
{src: "T_Skadi_Default_Icon.png", name:"Skadi" },
{src: "T_Sobek_Default_Icon.png", name:"Sobek" },
{src: "T_Sol_Default_Icon.png", name:"Sol" },
{src: "T_SunWukong_Default_Icon.png", name:"Sun Wukong" },
{src: "T_Sylvanus_Default_Icon.png", name:"Sylvanus" },
{src: "T_Thanatos_Default_Icon.png", name:"Thanatos" },
{src: "T_Thor_Default_Icon.png", name:"Thor" },
{src: "T_Tyr_Default_Icon.png", name:"Tyr" },
{src: "T_Ullr_Default_Icon.png", name:"Ullr" },
{src: "T_Vamana_Default_Icon.png", name: "Vamana" },
{src: "T_Vulcan_Default_Icon.png", name: "Vulcan" },
{src: "T_Xbalanque_Default_Icon.png", name: "Xbalanque" },
{src: "T_XingTian_Default_Icon.png", name: "XingTian" },
{src: "T_Ymir_Default_Icon.png", name: "Ymir" },
{src: "T_Zeus_Default_Icon.png", name: "Zeus" },
{src: "T_ZhongKui_Default_Icon.png", name: "ZhongKui"}
];